root: ./

structure:
  readme: homepage.md
  summary: TableOfContents.md
       
# https://docs.gitbook.com/integrations/github/content-configuration#redirects
redirects:
  services/web-engine/glossary: ./glossary.md

  # Manager 
  services/web-engine/interface: ./services/manager-ui
  services/web-engine/interface/editor: services/manager-ui/README.md
  services/content-schema: ./services/manager-ui/schema
  services/manager-ui/editor/version-control: ./services/manager-ui/editor/versions.md
  services/manager-ui/editor/save-and-quick-publish: ./services/manager-ui/editor/saving.md
  services/manager-ui/editor/custom-meta-tags: ./services/manager-ui/settings/instance-meta-tags.md

  # Accounts
  services/accounts: ./services/accounts-ui/README.md
  services/accounts/blueprints: ./services/accounts-ui/blueprints.md
  services/accounts/teams: ./services/accounts-ui/teams.md
  services/accounts/user-account-settings: ./services/accounts-ui/settings.md
  services/accounts/accounts-interface-all-instances-view: ./services/accounts-ui/instances.md

  # Guides
  services/web-engine/guides: ./guides
  services/web-engine/guides/adding-instances-to-ecosystems: ./guides/adding-instances-to-ecosystems.md
  services/web-engine/guides/the-connection-between-schema-content-and-code: ./guides/the-connection-between-schema-content-and-code.md
  services/web-engine/guides/how-to-launch-an-instance: ./guides/how-to-launch-an-instance.md

  # Getting Started
  content-instance: ./getting-started
  services/content/multi-locale-multi-lang-content-i18n: ./getting-started/i18n-multi-language.md

  # APIs
  apis/instances-rest-api: ./apis/instances-api.md  
  apis/accounts-rest-api: ./apis/accounts-api/README.md