root: ./

structure:
  readme: README.md
  summary: TableOfContents.md
       
redirects:
  services/web-engine/guides: guides
  services/web-engine/glossary: ./glossary.md
  services/web-engine/interface: services/manager-ui
  services/accounts: services/accounts-ui
  services/content/multi-locale-multi-lang-content-i18n: ./content-instance/multi-locale-multi-lang-content-i18n.md
  services/content-schema: services/manager-ui/schema
